const pokemons = [
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png',
        number: 1,
        name: 'Bulbasaur',
        type1: 'Grass',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/002.png',
        number: 2,
        name: 'Ivysaur',
        type1: 'Grass',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png',
        number: 3,
        name: 'Venusaur',
        type1: 'Grass',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png',
        number: 4,
        name: 'Charmander',
        type1: 'Fire',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/005.png',
        number: 5,
        name: 'Charmeleon',
        type1: 'Fire',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png',
        number: 6,
        name: 'Charizard',
        type1: 'Fire',
        type2: 'Flying',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png',
        number: 7,
        name: 'Squirtle',
        type1: 'Water',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/008.png',
        number: 8,
        name: 'Wartortle',
        type1: 'Water',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png',
        number: 9,
        name: 'Blastoise',
        type1: 'Water',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/010.png',
        number: 10,
        name: 'Caterpie',
        type1: 'Bug',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/011.png',
        number: 11,
        name: 'Metapod',
        type1: 'Bug',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png',
        number: 12,
        name: 'Butterfree',
        type1: 'Bug',
        type2: 'Flying',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png',
        number: 13,
        name: 'Weedle',
        type1: 'Bug',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/014.png',
        number: 14,
        name: 'Kakuna',
        type1: 'Bug',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/015.png',
        number: 15,
        name: 'Beedrill',
        type1: 'Bug',
        type2: 'Poison',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png',
        number: 16,
        name: 'Pidgey',
        type1: 'Normal',
        type2: 'Flying',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/017.png',
        number: 17,
        name: 'Pidgeotto',
        type1: 'Normal',
        type2: 'Flying',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png',
        number: 18,
        name: 'Pidgeot',
        type1: 'Normal',
        type2: 'Flying',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png',
        number: 19,
        name: 'Rattata',
        type1: 'Normal',
        type2: '',
    },
    {
        url: 'https://assets.pokemon.com/assets/cms2/img/pokedex/detail/020.png',
        number: 20,
        name: 'Raticate',
        type1: 'Normal',
        type2: '',
    },
];

module.exports = pokemons