[
  {
    rodada: 1,
    jogos: [
      {
        mandante: "TimeMandante_1_1",
        visitante: "TimeVisitante_1_1",
        placar: "1-2",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_2",
        visitante: "TimeVisitante_1_2",
        placar: "2-3",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_3",
        visitante: "TimeVisitante_1_3",
        placar: "3-0",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_4",
        visitante: "TimeVisitante_1_4",
        placar: "0-1",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_5",
        visitante: "TimeVisitante_1_5",
        placar: "1-2",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_6",
        visitante: "TimeVisitante_1_6",
        placar: "2-3",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_7",
        visitante: "TimeVisitante_1_7",
        placar: "3-0",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_8",
        visitante: "TimeVisitante_1_8",
        placar: "0-1",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_9",
        visitante: "TimeVisitante_1_9",
        placar: "1-2",
        data: "2025-04-01",
        concluido: true,
      },
      {
        mandante: "TimeMandante_1_10",
        visitante: "TimeVisitante_1_10",
        placar: "2-3",
        data: "2025-04-01",
        concluido: true,
      },
    ],
  },
  {
    rodada: 2,
    jogos: [
      {
        mandante: "TimeMandante_2_1",
        visitante: "TimeVisitante_2_1",
        placar: "1-2",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_2",
        visitante: "TimeVisitante_2_2",
        placar: "2-3",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_3",
        visitante: "TimeVisitante_2_3",
        placar: "3-0",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_4",
        visitante: "TimeVisitante_2_4",
        placar: "0-1",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_5",
        visitante: "TimeVisitante_2_5",
        placar: "1-2",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_6",
        visitante: "TimeVisitante_2_6",
        placar: "2-3",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_7",
        visitante: "TimeVisitante_2_7",
        placar: "3-0",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_8",
        visitante: "TimeVisitante_2_8",
        placar: "0-1",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_9",
        visitante: "TimeVisitante_2_9",
        placar: "1-2",
        data: "2025-04-02",
        concluido: true,
      },
      {
        mandante: "TimeMandante_2_10",
        visitante: "TimeVisitante_2_10",
        placar: "2-3",
        data: "2025-04-02",
        concluido: true,
      },
    ],
  },
  {
    rodada: 3,
    jogos: [
      {
        mandante: "TimeMandante_3_1",
        visitante: "TimeVisitante_3_1",
        placar: "1-2",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_2",
        visitante: "TimeVisitante_3_2",
        placar: "2-3",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_3",
        visitante: "TimeVisitante_3_3",
        placar: "3-0",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_4",
        visitante: "TimeVisitante_3_4",
        placar: "0-1",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_5",
        visitante: "TimeVisitante_3_5",
        placar: "1-2",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_6",
        visitante: "TimeVisitante_3_6",
        placar: "2-3",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_7",
        visitante: "TimeVisitante_3_7",
        placar: "3-0",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_8",
        visitante: "TimeVisitante_3_8",
        placar: "0-1",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_9",
        visitante: "TimeVisitante_3_9",
        placar: "1-2",
        data: "2025-04-03",
        concluido: true,
      },
      {
        mandante: "TimeMandante_3_10",
        visitante: "TimeVisitante_3_10",
        placar: "2-3",
        data: "2025-04-03",
        concluido: true,
      },
    ],
  },
  {
    rodada: 4,
    jogos: [
      {
        mandante: "TimeMandante_4_1",
        visitante: "TimeVisitante_4_1",
        placar: "1-2",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_2",
        visitante: "TimeVisitante_4_2",
        placar: "2-3",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_3",
        visitante: "TimeVisitante_4_3",
        placar: "3-0",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_4",
        visitante: "TimeVisitante_4_4",
        placar: "0-1",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_5",
        visitante: "TimeVisitante_4_5",
        placar: "1-2",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_6",
        visitante: "TimeVisitante_4_6",
        placar: "2-3",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_7",
        visitante: "TimeVisitante_4_7",
        placar: "3-0",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_8",
        visitante: "TimeVisitante_4_8",
        placar: "0-1",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_9",
        visitante: "TimeVisitante_4_9",
        placar: "1-2",
        data: "2025-04-04",
        concluido: true,
      },
      {
        mandante: "TimeMandante_4_10",
        visitante: "TimeVisitante_4_10",
        placar: "2-3",
        data: "2025-04-04",
        concluido: true,
      },
    ],
  },
  {
    rodada: 5,
    jogos: [
      {
        mandante: "TimeMandante_5_1",
        visitante: "TimeVisitante_5_1",
        placar: "1-2",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_2",
        visitante: "TimeVisitante_5_2",
        placar: "2-3",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_3",
        visitante: "TimeVisitante_5_3",
        placar: "3-0",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_4",
        visitante: "TimeVisitante_5_4",
        placar: "0-1",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_5",
        visitante: "TimeVisitante_5_5",
        placar: "1-2",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_6",
        visitante: "TimeVisitante_5_6",
        placar: "2-3",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_7",
        visitante: "TimeVisitante_5_7",
        placar: "3-0",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_8",
        visitante: "TimeVisitante_5_8",
        placar: "0-1",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_9",
        visitante: "TimeVisitante_5_9",
        placar: "1-2",
        data: "2025-04-05",
        concluido: true,
      },
      {
        mandante: "TimeMandante_5_10",
        visitante: "TimeVisitante_5_10",
        placar: "2-3",
        data: "2025-04-05",
        concluido: true,
      },
    ],
  },
  {
    rodada: 6,
    jogos: [
      {
        mandante: "TimeMandante_6_1",
        visitante: "TimeVisitante_6_1",
        placar: "1-2",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_2",
        visitante: "TimeVisitante_6_2",
        placar: "2-3",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_3",
        visitante: "TimeVisitante_6_3",
        placar: "3-0",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_4",
        visitante: "TimeVisitante_6_4",
        placar: "0-1",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_5",
        visitante: "TimeVisitante_6_5",
        placar: "1-2",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_6",
        visitante: "TimeVisitante_6_6",
        placar: "2-3",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_7",
        visitante: "TimeVisitante_6_7",
        placar: "3-0",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_8",
        visitante: "TimeVisitante_6_8",
        placar: "0-1",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_9",
        visitante: "TimeVisitante_6_9",
        placar: "1-2",
        data: "2025-04-06",
        concluido: true,
      },
      {
        mandante: "TimeMandante_6_10",
        visitante: "TimeVisitante_6_10",
        placar: "2-3",
        data: "2025-04-06",
        concluido: true,
      },
    ],
  },
  {
    rodada: 7,
    jogos: [
      {
        mandante: "TimeMandante_7_1",
        visitante: "TimeVisitante_7_1",
        placar: "1-2",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_2",
        visitante: "TimeVisitante_7_2",
        placar: "2-3",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_3",
        visitante: "TimeVisitante_7_3",
        placar: "3-0",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_4",
        visitante: "TimeVisitante_7_4",
        placar: "0-1",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_5",
        visitante: "TimeVisitante_7_5",
        placar: "1-2",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_6",
        visitante: "TimeVisitante_7_6",
        placar: "2-3",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_7",
        visitante: "TimeVisitante_7_7",
        placar: "3-0",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_8",
        visitante: "TimeVisitante_7_8",
        placar: "0-1",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_9",
        visitante: "TimeVisitante_7_9",
        placar: "1-2",
        data: "2025-04-07",
        concluido: true,
      },
      {
        mandante: "TimeMandante_7_10",
        visitante: "TimeVisitante_7_10",
        placar: "2-3",
        data: "2025-04-07",
        concluido: true,
      },
    ],
  },
  {
    rodada: 8,
    jogos: [
      {
        mandante: "TimeMandante_8_1",
        visitante: "TimeVisitante_8_1",
        placar: "1-2",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_2",
        visitante: "TimeVisitante_8_2",
        placar: "2-3",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_3",
        visitante: "TimeVisitante_8_3",
        placar: "3-0",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_4",
        visitante: "TimeVisitante_8_4",
        placar: "0-1",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_5",
        visitante: "TimeVisitante_8_5",
        placar: "1-2",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_6",
        visitante: "TimeVisitante_8_6",
        placar: "2-3",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_7",
        visitante: "TimeVisitante_8_7",
        placar: "3-0",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_8",
        visitante: "TimeVisitante_8_8",
        placar: "0-1",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_9",
        visitante: "TimeVisitante_8_9",
        placar: "1-2",
        data: "2025-04-08",
        concluido: true,
      },
      {
        mandante: "TimeMandante_8_10",
        visitante: "TimeVisitante_8_10",
        placar: "2-3",
        data: "2025-04-08",
        concluido: true,
      },
    ],
  },
  {
    rodada: 9,
    jogos: [
      {
        mandante: "TimeMandante_9_1",
        visitante: "TimeVisitante_9_1",
        placar: "1-2",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_2",
        visitante: "TimeVisitante_9_2",
        placar: "2-3",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_3",
        visitante: "TimeVisitante_9_3",
        placar: "3-0",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_4",
        visitante: "TimeVisitante_9_4",
        placar: "0-1",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_5",
        visitante: "TimeVisitante_9_5",
        placar: "1-2",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_6",
        visitante: "TimeVisitante_9_6",
        placar: "2-3",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_7",
        visitante: "TimeVisitante_9_7",
        placar: "3-0",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_8",
        visitante: "TimeVisitante_9_8",
        placar: "0-1",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_9",
        visitante: "TimeVisitante_9_9",
        placar: "1-2",
        data: "2025-04-09",
        concluido: true,
      },
      {
        mandante: "TimeMandante_9_10",
        visitante: "TimeVisitante_9_10",
        placar: "2-3",
        data: "2025-04-09",
        concluido: true,
      },
    ],
  },
  {
    rodada: 10,
    jogos: [
      {
        mandante: "TimeMandante_10_1",
        visitante: "TimeVisitante_10_1",
        placar: "1-2",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_2",
        visitante: "TimeVisitante_10_2",
        placar: "2-3",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_3",
        visitante: "TimeVisitante_10_3",
        placar: "3-0",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_4",
        visitante: "TimeVisitante_10_4",
        placar: "0-1",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_5",
        visitante: "TimeVisitante_10_5",
        placar: "1-2",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_6",
        visitante: "TimeVisitante_10_6",
        placar: "2-3",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_7",
        visitante: "TimeVisitante_10_7",
        placar: "3-0",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_8",
        visitante: "TimeVisitante_10_8",
        placar: "0-1",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_9",
        visitante: "TimeVisitante_10_9",
        placar: "1-2",
        data: "2025-04-10",
        concluido: true,
      },
      {
        mandante: "TimeMandante_10_10",
        visitante: "TimeVisitante_10_10",
        placar: "2-3",
        data: "2025-04-10",
        concluido: true,
      },
    ],
  },
  {
    rodada: 11,
    jogos: [
      {
        mandante: "TimeMandante_11_1",
        visitante: "TimeVisitante_11_1",
        placar: "1-2",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_2",
        visitante: "TimeVisitante_11_2",
        placar: "2-3",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_3",
        visitante: "TimeVisitante_11_3",
        placar: "3-0",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_4",
        visitante: "TimeVisitante_11_4",
        placar: "0-1",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_5",
        visitante: "TimeVisitante_11_5",
        placar: "1-2",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_6",
        visitante: "TimeVisitante_11_6",
        placar: "2-3",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_7",
        visitante: "TimeVisitante_11_7",
        placar: "3-0",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_8",
        visitante: "TimeVisitante_11_8",
        placar: "0-1",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_9",
        visitante: "TimeVisitante_11_9",
        placar: "1-2",
        data: "2025-04-11",
        concluido: true,
      },
      {
        mandante: "TimeMandante_11_10",
        visitante: "TimeVisitante_11_10",
        placar: "2-3",
        data: "2025-04-11",
        concluido: true,
      },
    ],
  },
  {
    rodada: 12,
    jogos: [
      {
        mandante: "TimeMandante_12_1",
        visitante: "TimeVisitante_12_1",
        placar: "1-2",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_2",
        visitante: "TimeVisitante_12_2",
        placar: "2-3",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_3",
        visitante: "TimeVisitante_12_3",
        placar: "3-0",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_4",
        visitante: "TimeVisitante_12_4",
        placar: "0-1",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_5",
        visitante: "TimeVisitante_12_5",
        placar: "1-2",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_6",
        visitante: "TimeVisitante_12_6",
        placar: "2-3",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_7",
        visitante: "TimeVisitante_12_7",
        placar: "3-0",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_8",
        visitante: "TimeVisitante_12_8",
        placar: "0-1",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_9",
        visitante: "TimeVisitante_12_9",
        placar: "1-2",
        data: "2025-04-12",
        concluido: true,
      },
      {
        mandante: "TimeMandante_12_10",
        visitante: "TimeVisitante_12_10",
        placar: "2-3",
        data: "2025-04-12",
        concluido: true,
      },
    ],
  },
  {
    rodada: 13,
    jogos: [
      {
        mandante: "TimeMandante_13_1",
        visitante: "TimeVisitante_13_1",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_2",
        visitante: "TimeVisitante_13_2",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_3",
        visitante: "TimeVisitante_13_3",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_4",
        visitante: "TimeVisitante_13_4",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_5",
        visitante: "TimeVisitante_13_5",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_6",
        visitante: "TimeVisitante_13_6",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_7",
        visitante: "TimeVisitante_13_7",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_8",
        visitante: "TimeVisitante_13_8",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_9",
        visitante: "TimeVisitante_13_9",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
      {
        mandante: "TimeMandante_13_10",
        visitante: "TimeVisitante_13_10",
        placar: "-",
        data: "2025-06-22",
        concluido: false,
      },
    ],
  },
];
