let hospedagens = [
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
    { nome: "Suit Resort da Costa Azul", preco: 320.0 },
    { nome: "Suit Resort da Costa Verde", preco: 420.0 },
];

let resultado = document.getElementById("resultado")

hospedagens.forEach(element => {
    resultado.innerHTML += `<p>${element.nome}</p>`
});