export const sintomas = [
  "Abaulamento",
  "Abdomen em tábua",
  "Acolia fecal",
  "Aftas",
  "Agitação",
  "Alteração do estado mental",
  "Anemia",
  "Anorexia",
  "Artrite infecciosa",
  "Artropatia de Charcot",
  "Astenia",
  "Ataxia sensitiva",
  "Atraso no crescimento",
  "Atrofia muscular",
  "Aversão ao tabaco",
  "Bradicardia",
  "Calafrios",
  "Cansaço",
  "Cefaleia",
  "Colúria",
  "Coma",
  "Confusão mental",
  "Convulsão",
  "Corrimento vaginal",
  "Cianose",
  "Dermatite herpetiforme",
  "Desidratação",
  "Dificuldade de ganhar peso",
  "Dismenorreia",
  "Dispareunia",
  "Dispneia",
  "Distensão abdominal",
  "Disúria",
  "Dor articular",
  "Dor súbita ao exercício",
  "Dor torácica",
  "Enterorragia",
  "Episclerite",
  "Equimose",
  "Eritema cutâneo",
  "Eritema nodoso",
  "Esteatorreia",
  "Fadiga",
  "Flatos vaginal",
  "Flatulência",
  "Febre",
  "Fraqueza",
  "Fraqueza muscular",
  "Globus faringeo",
  "Hematêmese",
  "Hematoquisia",
  "Hematúria",
  "Hiperestesia",
  "Hipersensibilidade da parede abdominal",
  "Hipertensão",
  "Hipotensão",
  "Inquietação",
  "Icterícia",
  "Impotência",
  "Infertilidade",
  "Insônia",
  "Intolerância ao álcool",
  "Letargia",
  "Manchas rosadas",
  "Massa palpável",
  "Mau hálito",
  "Melena",
  "Metrorragia",
  "Mialgia",
  "Miose",
  "Náusea",
  "Noctúria",
  "Obnubilação",
  "Oligúria",
  "Orquite",
  "Osteopenia",
  "Palidez cutânea",
  "Palpitação",
  "Parestesia",
  "Pneumatúria",
  "Perda ponderal",
  "Perda da propriocepção",
  "Perda dos reflexos periféricos",
  "Perda da sensibilidade vibratória",
  "Plenitude pós prandial",
  "Polidipsia",
  "Poliúria",
  "Posição antálgica",
  "Proctalgia",
  "Prurido",
  "Pulso paradoxal",
  "Púrpura palpável",
  "Queimação",
  "Refluxo",
  "Respiração de Kussmaul",
  "Rouquidão",
  "Sonolência",
  "Sudorese",
  "Taquicardia",
  "Taquipnéia",
  "Tenesmo",
  "Tonteira",
  "Tosse produtiva",
  "Tosse seca",
  "Toxemia",
  "Turgência jugular",
  "Urgência miccional",
  "Urina escura - cor de vinho",
  "Vesículas ou Pápulas",
  "Vômito",
  "Wrist drop (paralisia do punho)",
];
