const data = [
    {
        id: 1,
        name: 'Alberto Fernandes Couto',
        email: 'albertofc@email.com',
        password: 'alberto_password',
    },
    {
        id: 2,
        name: 'Adenil Souza',
        email: 'adenils@email.com',
        password: 'adenils_password',
    },
    {
        id: 3,
        name: 'Carlos Silva',
        email: 'carlos@email.com',
        password: 'carlos_password',
    },
    {
        id: 4,
        name: 'Daniela Rodrigues',
        email: 'daniela@email.com',
        password: 'daniela_password',
    },
    {
        id: 5,
        name: 'Eduardo Lima',
        email: 'eduardo@email.com',
        password: 'eduardo_password',
    },
    {
        id: 6,
        name: 'Fernanda Santos',
        email: 'fernanda@email.com',
        password: 'fernanda_password',
    },
    {
        id: 7,
        name: 'Gabriel Alves',
        email: 'gabriel@email.com',
        password: 'gabriel_password',
    },
    {
        id: 8,
        name: 'Helena Oliveira',
        email: 'helena@email.com',
        password: 'helena_password',
    },
    {
        id: 9,
        name: 'Isabela Costa',
        email: 'isabela@email.com',
        password: 'isabela_password',
    },
    {
        id: 10,
        name: 'João Pereira',
        email: 'joao@email.com',
        password: 'joao_password',
    },
    {
        id: 11,
        name: 'Karen Souza',
        email: 'karen@email.com',
        password: 'karen_password',
    },
    {
        id: 12,
        name: 'Lucas Santos',
        email: 'lucas@email.com',
        password: 'lucas_password',
    },
    {
        id: 13,
        name: 'Maria Ferreira',
        email: 'maria@email.com',
        password: 'maria_password',
    },
    {
        id: 14,
        name: 'Natalia Lima',
        email: 'natalia@email.com',
        password: 'natalia_password',
    },
    {
        id: 15,
        name: 'Otavio Almeida',
        email: 'otavio@email.com',
        password: 'otavio_password',
    },
    {
        id: 16,
        name: 'Paula Ribeiro',
        email: 'paula@email.com',
        password: 'paula_password',
    },
    {
        id: 17,
        name: 'Ricardo Gomes',
        email: 'ricardo@email.com',
        password: 'ricardo_password',
    },
    {
        id: 18,
        name: 'Sofia Fernandes',
        email: 'sofia@email.com',
        password: 'sofia_password',
    },
    {
        id: 19,
        name: 'Thiago Oliveira',
        email: 'thiago@email.com',
        password: 'thiago_password',
    },
    {
        id: 20,
        name: 'Vanessa Silva',
        email: 'vanessa@email.com',
        password: 'vanessa_password',
    },
    {
        id: 21,
        name: 'Wagner Santos',
        email: 'wagner@email.com',
        password: 'wagner_password',
    },
    {
        id: 22,
        name: 'Xavier Costa',
        email: 'xavier@email.com',
        password: 'xavier_password',
    },
    {
        id: 23,
        name: 'Yasmin Rodrigues',
        email: 'yasmin@email.com',
        password: 'yasmin_password',
    },
    {
        id: 24,
        name: 'Zara Alves',
        email: 'zara@email.com',
        password: 'zara_password',
    },
    {
        id: 25,
        name: 'Andre Oliveira',
        email: 'andre@email.com',
        password: 'andre_password',
    },
    {
        id: 26,
        name: 'Bianca Pereira',
        email: 'bianca@email.com',
        password: 'bianca_password',
    },
    {
        id: 27,
        name: 'Cesar Fernandes',
        email: 'cesar@email.com',
        password: 'cesar_password',
    },
    {
        id: 28,
        name: 'Debora Souza',
        email: 'debora@email.com',
        password: 'debora_password',
    },
    {
        id: 29,
        name: 'Elisa Lima',
        email: 'elisa@email.com',
        password: 'elisa_password',
    },
    {
        id: 30,
        name: 'Fernando Gomes',
        email: 'fernando@email.com',
        password: 'fernando_password',
    },
];

module.exports = data;

